### ISSUE TITLE
Backwards compatibility of encodedpolyline

### ISSUE THREAD

**Issue by aoles** [GIScience/openelevationservice#16]
Recent updates to the package introduced improvements to `encodedpolyline` format by adding support for increased precision. While implementing the new `encodedpolyline6` format the originally accepted `encodedpolyline` parameter value was renamed to `encodedpolyline5`.

This approach, however, breaks backwards compatibility. Apart from it there is also no particular reason to use a different name for the format which follows Google's [encoded polyline](https://developers.google.com/maps/documentation/utilities/polylinealgorithm) standard. Please consider renaming `encodedpolyline5` to just `encodedpolyline`.

Cheers,
Andrzej

**Comment by nilsnolde** [comment]
Sorry, just seeing this.

No, it's accepting `encodedpolyline` on top of `encodedpolyline5` (both doing the same thing) and I think it always did. Docs are not exactly showing that, true.

**Comment by aoles** [comment]
Thanks a lot for clarifying, I will then stick to `encodedpolyline`.
