### ISSUE TITLE
Header Error for 'Content-Type': 'application/json;charset=utf-8'

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openelevationservice#17]
API should also accept `'Content-Type': 'application/json;charset=utf-8'` as request Header.
This kind of requests currently fails with:
```
{
"code": 4001,
"message": "HeaderError: Content-Type header is not application/json"
}
```

**Comment by TheGreatRefrigerator** [comment]
I solved this by overriding the default Headers on the Vue Frontend.
Feel free to implement or close :)

**Comment by nilsnolde** [comment]
oopsie, yep, will fix that. thx for the pointer!
