### ISSUE TITLE
HTTP Method not allowed

### ISSUE THREAD

**Issue by webmap2015** [GIScience/openelevationservice#26]
Hi,

There is an error

jQuery.getJSON('https://api.openrouteservice.org/elevation/line?api_key=my-api-key&geometry=[[13.349762,38.11295],[12.638397,37.645772]]', function (data) {
	console.log(data);
}

Chrome developer result:

{code: 405, message: "HTTP Method not allowed"}

Thanks.

**Comment by TheGreatRefrigerator** [comment]
Hi @webmap2015,

the elevation service only does have a POST endpoint for `/line`, please use POST if you request heights for line features
